-- telescope color tweaks based on NvChad, see:
-- https://github.com/NvChad/NvChad/blob/bccd8e4ab9942c57eaeee76c7e41c2b41cba17c4/lua/colors/highlights.lua#L119C1-L131C33

return {
    {
        "Mofiqul/dracula.nvim",
        lazy = false,
        priority = 1000,
        opts = {
            italic_comment = true,
            overrides = function(colors)
                return {
                    ["@character"] = { link = "@string" },
                    ["@constructor.lua"] = { fg = colors.fg },
                    ["@field"] = { fg = colors.fg },
                    ["@field.yaml"] = { fg = colors.cyan },
                    ["@function.macro"] = { fg = colors.green, italic = true },
                    ["@keyword"] = { link = "Keyword" },
                    ["@keyword.function"] = { link = "Keyword" },
                    ["@label.markdown"] = { fg = colors.green },
                    ["@lsp.mod.constant.rust"] = { link = "@constant" },
                    ["@lsp.mod.mutable.rust"] = { underline = true },
                    ["@lsp.mod.static.rust"] = { link = "@constant" },
                    ["@lsp.type.builtinAttribute.rust"] = { fg = colors.fg },
                    ["@lsp.type.character.rust"] = { link = "@string" },
                    ["@lsp.type.decorator.rust"] = { fg = colors.fg },
                    ["@lsp.type.deriveHelper.rust"] = { fg = colors.fg },
                    ["@lsp.type.enumMember"] = { fg = colors.orange },
                    ["@lsp.type.interface"] = { fg = colors.cyan, italic = true },
                    ["@lsp.type.keyword"] = { link = "Keyword" },
                    ["@lsp.type.macro"] = { link = "@function.macro" },
                    ["@lsp.type.namespace"] = { fg = colors.cyan },
                    ["@lsp.type.parameter"] = { fg = colors.orange, italic = true },
                    ["@lsp.type.property"] = { fg = colors.fg },
                    ["@lsp.type.selfKeyword.rust"] = { link = "Keyword" },
                    ["@lsp.type.selfTypeKeyword.rust"] = { link = "Keyword" },
                    ["@lsp.type.typeAlias"] = { link = "@type" },
                    ["@lsp.type.typeParameter"] = { link = "@type" },
                    ["@lsp.typemod.method.static.rust"] = { link = "@function" },
                    ["@markup.bold.markdown_inline"] = { fg = colors.orange, bold = true },
                    ["@markup.heading"] = { fg = colors.purple, bold = true },
                    ["@markup.italic.markdown_inline"] = { fg = colors.orange, italic = true },
                    ["@markup.link"] = { fg = colors.fg },
                    ["@markup.link.label.markdown_inline"] = { fg = colors.pink },
                    ["@markup.link.url"] = { fg = colors.cyan, underline = true },
                    ["@markup.raw.block"] = { fg = colors.fg },
                    ["@markup.raw.delimiter.markdown"] = { fg = colors.green },
                    ["@markup.raw.delimiter.markdown_inline"] = { fg = colors.green },
                    ["@markup.raw.markdown_inline"] = { fg = colors.green },
                    ["@module"] = { fg = colors.cyan },
                    ["@numer.float"] = { link = "@number" },
                    ["@parameter"] = { fg = colors.orange, italic = true },
                    ["@punctuation.delimiter.json"] = { link = "Keyword" },
                    ["@punctuation.delimiter.yaml"] = { link = "Keyword" },
                    ["@punctuation.special.markdown"] = { fg = colors.pink },
                    ["@punctuation.special.rust"] = { fg = colors.fg },
                    ["@string.escape"] = { link = "Keyword" },
                    ["@string.regexp"] = { link = "@string" },
                    ["@type"] = { fg = colors.cyan },
                    ["@type.builtin"] = { link = "@type" },
                    ["@variable.member"] = { fg = colors.fg },
                    ["@variable.parameter"] = { link = "@parameter" },
                    Character = { link = "String" },
                    Constant = { fg = colors.purple },
                    CursorLine = { bg = "#353747" },
                    DiagnosticUnnecessary = { fg = colors.comment },
                    DiffChange = { fg = colors.yellow },
                    diffIndexLine = { fg = colors.fg },
                    diffSubname = { fg = colors.fg },
                    Function = { fg = colors.green },
                    GitSignsAddPreview = { fg = colors.bright_green },
                    GitSignsChange = { fg = colors.yellow },
                    GitSignsChangeLn = { fg = colors.black, bg = colors.yellow },
                    GitSignsDeletePreview = { fg = colors.red },
                    Keyword = { fg = colors.pink },
                    Keywords = { link = "Keyword" },
                    LazyNormal = { link = "NeoTreeNormal" },
                    LspInlayHint = { fg = "#a2a7c4" },
                    LspReferenceRead = { bg = "#506473" },
                    LspReferenceText = { bg = "#506473" },
                    LspReferenceWrite = { bg = "#506473" },
                    NeoTreeGitModified = { fg = colors.yellow },
                    NeoTreeGitUnstaged = { fg = colors.yellow },
                    ps1Boolean = { link = "@number" },
                    ps1Cmdlet = { link = "@function" },
                    ps1Function = { link = "@function" },
                    ps1Operator = { link = "@operator" },
                    ps1Variable = { link = "@variable" },
                    TelescopeNormal = { fg = colors.fg, bg = colors.menu },
                    TelescopePreviewBorder = { fg = colors.menu, bg = colors.menu },
                    TelescopePreviewTitle = { fg = colors.green, reverse = true, bold = true },
                    TelescopePromptBorder = { fg = colors.bg, bg = colors.bg },
                    TelescopePromptNormal = { fg = colors.fg, bg = colors.bg },
                    TelescopePromptTitle = { fg = colors.purple, reverse = true, bold = true },
                    TelescopeResultsBorder = { fg = colors.menu, bg = colors.menu },
                    TelescopeResultsDiffChange = { fg = colors.yellow },
                    TelescopeResultsTitle = {
                        fg = colors.green,
                        bg = colors.menu,
                        reverse = true,
                        bold = true,
                    },
                    ToggleTermBorder = { fg = colors.comment },
                    zshDeref = { link = "@variable" },
                    zshFunction = { link = "@function" },
                    zshOperator = { link = "@operator" },
                    zshShortDeref = { link = "zshDeref" },
                    zshSubstDelim = { link = "@variable" },
                    zshSubstQuoted = { link = "@variable" },
                    zshTypes = { link = "@keyword" },
                }
            end,
        },
        config = require("user.theme").make_config("dracula"),
    },
}
