return {
    {
        "Mofiqul/dracula.nvim",
        lazy = false,
        priority = 1000,
        opts = {
            italic_comment = true,
            overrides = function(colors)
                return {
                    Constant = { fg = colors.purple },
                    CursorLine = { bg = "#353747" },
                    DiagnosticUnnecessary = { fg = colors.comment },
                    DiffChange = { fg = colors.yellow },
                    Function = { fg = colors.green },
                    GitSignsAddPreview = { fg = colors.bright_green },
                    GitSignsChange = { fg = colors.yellow },
                    GitSignsChangeLn = { fg = colors.black, bg = colors.yellow },
                    GitSignsDeletePreview = { fg = colors.red },
                    Keyword = { fg = colors.pink },
                    Keywords = { link = "Keyword" },
                    LspReferenceRead = { bg = "#424450" },
                    LspReferenceText = { bg = "#424450" },
                    LspReferenceWrite = { bg = "#424450" },
                    NeoTreeGitModified = { fg = colors.yellow },
                    NeoTreeGitUnstaged = { fg = colors.yellow },
                    TelescopeResultsDiffChange = { fg = colors.yellow },
                    diffIndexLine = { fg = colors.fg },
                    diffSubname = { fg = colors.fg },
                    ps1Boolean = { link = "@number" },
                    ps1Cmdlet = { link = "@function" },
                    ps1Function = { link = "@function" },
                    ps1Operator = { link = "@operator" },
                    ps1Variable = { link = "@variable" },
                    zshDeref = { link = "@variable" },
                    zshFunction = { link = "@function" },
                    zshOperator = { link = "@operator" },
                    zshShortDeref = { link = "zshDeref" },
                    zshSubstDelim = { link = "@variable" },
                    zshSubstQuoted = { link = "@variable" },
                    zshTypes = { link = "@keyword" },
                    ["@constructor.lua"] = { fg = colors.fg },
                    ["@field"] = { fg = colors.fg },
                    ["@field.yaml"] = { fg = colors.cyan },
                    ["@function.macro"] = { fg = colors.green, italic = true },
                    ["@keyword"] = { link = "Keyword" },
                    ["@keyword.function"] = { link = "Keyword" },
                    ["@label.markdown"] = { fg = colors.green },
                    ["@lsp.mod.constant.rust"] = { link = "@constant" },
                    ["@lsp.mod.mutable.rust"] = { underline = true },
                    ["@lsp.mod.static.rust"] = { link = "@constant" },
                    ["@lsp.type.builtinAttribute.rust"] = { fg = colors.fg },
                    ["@lsp.type.decorator.rust"] = { fg = colors.fg },
                    ["@lsp.type.enumMember"] = { fg = colors.orange },
                    ["@lsp.type.interface"] = { fg = colors.cyan, italic = true },
                    ["@lsp.type.macro"] = { link = "@function.macro" },
                    ["@lsp.type.namespace"] = { fg = colors.cyan },
                    ["@lsp.type.parameter"] = { fg = colors.orange, italic = true },
                    ["@lsp.type.property"] = { fg = colors.fg },
                    ["@markup.bold.markdown_inline"] = { fg = colors.orange, bold = true },
                    ["@markup.heading"] = { fg = colors.purple, bold = true },
                    ["@markup.italic.markdown_inline"] = { fg = colors.orange, italic = true },
                    ["@markup.link"] = { fg = colors.fg },
                    ["@markup.link.label.markdown_inline"] = { fg = colors.pink },
                    ["@markup.link.url"] = { fg = colors.cyan, underline = true },
                    ["@markup.raw.block"] = { fg = colors.fg },
                    ["@markup.raw.delimiter.markdown"] = { fg = colors.green },
                    ["@markup.raw.delimiter.markdown_inline"] = { fg = colors.green },
                    ["@markup.raw.markdown_inline"] = { fg = colors.green },
                    ["@module"] = { fg = colors.cyan },
                    ["@parameter"] = { fg = colors.orange, italic = true },
                    ["@punctuation.delimiter.json"] = { fg = colors.pink },
                    ["@punctuation.delimiter.yaml"] = { fg = colors.pink },
                    ["@punctuation.special.markdown"] = { fg = colors.pink },
                    ["@punctuation.special.rust"] = { fg = colors.fg },
                    ["@type"] = { fg = colors.cyan },
                    ["@type.builtin"] = { link = "@type" },
                    ["@variable.member"] = { fg = colors.fg },
                    ["@variable.parameter"] = { link = "@parameter" },
                }
            end,
        },
        config = function(_, opts)
            if require("user.theme").name == "dracula" then
                require("dracula").setup(opts)
                vim.cmd([[colorscheme dracula]])
            end
        end,
    },
}
